// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {".?AVbad_alloc@std@@", 0ULL, "class"},
    {".?AVbad_array_new_length@std@@", 0ULL, "class"},
    {".?AVexception@std@@", 0ULL, "class"},
    {".?AVtype_info@@", 0ULL, "class"},
    {"CRefCountImpl<class CWarpPalAlphaBltExtension>", 0ULL, "layout-evidence"},
    {"CRefCountImpl<class CWarpPalCreateSharedResourceExtension>", 0ULL, "layout-evidence"},
    {"CRefCountImpl<class CWarpPalExtensionFactory>", 0ULL, "layout-evidence"},
    {"CRefCountImpl<class CWarpPalFlushAndWaitExtension>", 0ULL, "layout-evidence"},
    {"CRefCountImpl<class CWarpPalLockSubresourceExtension>", 0ULL, "layout-evidence"},
    {"CWarpExtensionBase<class IWarpPalAlphaBltExtension>", 0ULL, "layout-evidence"},
    {"CWarpExtensionBase<class IWarpPalCreateSharedResourceExtension>", 0ULL, "layout-evidence"},
    {"CWarpExtensionBase<class IWarpPalFlushAndWaitExtension>", 0ULL, "layout-evidence"},
    {"CWarpExtensionBase<class IWarpPalLockSubresourceExtension>", 0ULL, "layout-evidence"},
    {"CWarpPalAlphaBltExtension", 0ULL, "layout-evidence"},
    {"CWarpPalCreateSharedResourceExtension", 0ULL, "layout-evidence"},
    {"CWarpPalExtensionFactory", 0ULL, "layout-evidence"},
    {"CWarpPalFlushAndWaitExtension", 0ULL, "layout-evidence"},
    {"CWarpPalLockSubresourceExtension", 0ULL, "layout-evidence"},
    {"IWarpPalAlphaBltExtension", 0ULL, "layout-evidence"},
    {"IWarpPalFlushAndWaitExtension", 0ULL, "layout-evidence"},
    {"IWarpPalLockSubresourceExtension", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::ComPtr<class CRefCountImpl<class CWarpPalExtensionFactory> >", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::ComPtr<class IWarpPrivateAPI>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::ComPtrRef<class Microsoft::WRL::ComPtr<class IWarpPrivateAPI> >", 0ULL, "layout-evidence"},
    {"WarpExtension_AlphaBltEx2", 0ULL, "layout-evidence"},
    {"WarpExtension_Base", 0ULL, "layout-evidence"},
    {"WarpExtension_BeginCreateSharedResource", 0ULL, "layout-evidence"},
    {"WarpExtension_EndCreateSharedResource", 0ULL, "layout-evidence"},
    {"WarpExtension_FlushAndWait", 0ULL, "layout-evidence"},
    {"WarpExtension_LockSubresource", 0ULL, "layout-evidence"},
    {"WarpExtension_QueryExtension", 0ULL, "layout-evidence"},
    {"WarpExtension_UnlockSubresource", 0ULL, "layout-evidence"},
    {"WarpRasterStates", 0ULL, "layout-evidence"},
    {"WarpTextureState", 0ULL, "layout-evidence"},
    {"std", 0ULL, "layout-evidence"},
    {"std::_Atomic_integral<int, 4>", 0ULL, "layout-evidence"},
    {"std::_Atomic_integral_facade<int>", 0ULL, "layout-evidence"},
    {"std::_Atomic_storage<int, 4>", 0ULL, "layout-evidence"},
    {"std::atomic<int>", 0ULL, "layout-evidence"},
    {"std::bad_alloc", 0ULL, "layout-evidence"},
    {"std::bad_array_new_length", 0ULL, "layout-evidence"},
    {"std::exception", 0ULL, "layout-evidence"},
    {"std::invalid_argument", 0ULL, "layout-evidence"},
    {"std::logic_error", 0ULL, "layout-evidence"},
    {"type_info", 0ULL, "layout-evidence"},
    {"wil", 0ULL, "layout-evidence"},
    {"wil::DiagnosticsInfo", 0ULL, "layout-evidence"},
    {"wil::ResultException", 0ULL, "layout-evidence"},
    {"wil::StoredFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details", 0ULL, "layout-evidence"},
    {"wil::details::ResultStatus", 0ULL, "layout-evidence"},
    {"wil::details::in1diag3", 0ULL, "layout-evidence"},
    {"wil::details::pointer_range<struct wil::details_abi::ThreadLocalFailureInfo *>", 0ULL, "layout-evidence"},
    {"wil::details::shared_buffer", 0ULL, "layout-evidence"},
    {"wil::details_abi", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorage<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::SemaphoreValue", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<class wil::details::ThreadFailureCallbackHolder *>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<struct wil::details_abi::ThreadLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<struct wil::details_abi::ThreadLocalData>::Node", 0ULL, "layout-evidence"},
    {"wil::last_error_context", 0ULL, "layout-evidence"},
    {"wil::process_heap_deleter", 0ULL, "layout-evidence"},
    {"winrt", 0ULL, "layout-evidence"},
    {"winrt::com_ptr<struct winrt::impl::IErrorInfo>", 0ULL, "layout-evidence"},
    {"winrt::handle_type<struct winrt::impl::bstr_traits>", 0ULL, "layout-evidence"},
    {"winrt::handle_type<struct winrt::impl::heap_traits>", 0ULL, "layout-evidence"},
    {"winrt::handle_type<struct winrt::impl::hstring_traits>", 0ULL, "layout-evidence"},
    {"winrt::hresult", 0ULL, "layout-evidence"},
    {"winrt::hresult_error", 0ULL, "layout-evidence"},
    {"winrt::hstring", 0ULL, "layout-evidence"},
    {"winrt::impl", 0ULL, "layout-evidence"},
    {"winrt::impl::atomic_ref_count", 0ULL, "layout-evidence"},
    {"wistd", 0ULL, "layout-evidence"},
    {"wistd::__compressed_pair<void *, struct wil::process_heap_deleter>", 0ULL, "layout-evidence"},
    {"wistd::__compressed_pair_elem<struct wil::process_heap_deleter, 1, 1>", 0ULL, "layout-evidence"},
    {"wistd::__compressed_pair_elem<void *, 0, 0>", 0ULL, "layout-evidence"},
    {"wistd::unique_ptr<void, struct wil::process_heap_deleter>", 0ULL, "layout-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0x20ACU, "??0bad_array_new_length@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0x20F0U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0x2114U, "??1bad_array_new_length@std@@UEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 0ULL, 8U, "write", 0x2130U, "??_Gbad_array_new_length@std@@UEAAPEAXI@Z", "likely"},
    {"std::bad_array_new_length", nullptr, 8ULL, 16U, "write", 0x20ACU, "??0bad_array_new_length@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_array_new_length", nullptr, 8ULL, 8U, "write", 0x20F0U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"std::bad_array_new_length", nullptr, 16ULL, 8U, "read-write", 0x20F0U, "??0bad_array_new_length@std@@QEAA@XZ", "likely"},
    {"type_info", nullptr, 0ULL, 8U, "write", 0x1960U, "??_Gtype_info@@UEAAPEAXI@Z", "likely"},
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {".?AVbad_alloc@std@@", ".?AVbad_alloc@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_alloc@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVbad_array_new_length@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVbad_alloc@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVbad_array_new_length@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVexception@std@@", ".?AVexception@std@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {".?AVtype_info@@", ".?AVtype_info@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const type_info::`vftable'", 0x12008U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::exception::`vftable'", 0x12028U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::bad_alloc::`vftable'", 0x12040U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::bad_array_new_length::`vftable'", 0x12058U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::logic_error::`vftable'", 0x12068U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::invalid_argument::`vftable'", 0x12078U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::ResultException::`vftable'", 0x12088U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefCountImpl<class CWarpPalExtensionFactory>::`vftable'", 0x12098U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefCountImpl<class CWarpPalLockSubresourceExtension>::`vftable'", 0x120B8U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefCountImpl<class CWarpPalFlushAndWaitExtension>::`vftable'", 0x120E0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefCountImpl<class CWarpPalCreateSharedResourceExtension>::`vftable'", 0x12100U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefCountImpl<class CWarpPalAlphaBltExtension>::`vftable'", 0x12128U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const IWarpPalAlphaBltExtension::`vftable'", 0x12170U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const IWarpPalCreateSharedResourceExtension::`vftable'", 0x121B8U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const IWarpPalExtensionFactory::`vftable'", 0x121E0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CWarpExtensionBase<class IWarpPalAlphaBltExtension>::`vftable'", 0x12200U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CWarpExtensionBase<class IWarpPalCreateSharedResourceExtension>::`vftable'", 0x12248U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CWarpExtensionBase<class IWarpPalFlushAndWaitExtension>::`vftable'", 0x12270U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CWarpExtensionBase<class IWarpPalLockSubresourceExtension>::`vftable'", 0x12290U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0x12008U, 0U, 0x1960U, nullptr, nullptr, true, 0},
    {0x12028U, 0U, 0x4E00U, nullptr, nullptr, true, 0},
    {0x12028U, 1U, 0xBAC0U, "?what@exception@std@@UEBAPEBDXZ", "public: virtual char const * __cdecl std::exception::what(void) const", false, 0},
    {0x12040U, 0U, 0x4DB0U, nullptr, nullptr, true, 0},
    {0x12040U, 1U, 0xBAC0U, nullptr, nullptr, true, 0},
    {0x12058U, 0U, 0x2130U, nullptr, nullptr, true, 0},
    {0x12058U, 1U, 0xBAC0U, nullptr, nullptr, true, 0},
    {0x12068U, 0U, 0x4DB0U, nullptr, nullptr, true, 0},
    {0x12068U, 1U, 0xBAC0U, nullptr, nullptr, true, 0},
    {0x12078U, 0U, 0x4E50U, nullptr, nullptr, true, 0},
    {0x12078U, 1U, 0xBAC0U, nullptr, nullptr, true, 0},
    {0x12088U, 0U, 0x4D60U, nullptr, nullptr, true, 0},
    {0x12088U, 1U, 0xB940U, "?what@ResultException@wil@@UEBAPEBDXZ", "public: virtual char const * __cdecl wil::ResultException::what(void) const", false, 0},
    {0x12098U, 0U, 0xE450U, nullptr, nullptr, true, 0},
    {0x12098U, 1U, 0xCE20U, "?AddRef@?$CRefCountImpl@VCWarpPalExtensionFactory@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalExtensionFactory>::AddRef(void)", false, 0},
    {0x12098U, 2U, 0xE5D0U, "?Release@?$CRefCountImpl@VCWarpPalExtensionFactory@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalExtensionFactory>::Release(void)", false, 0},
    {0x12098U, 3U, 0xCFA0U, nullptr, nullptr, true, 0},
    {0x120B8U, 0U, 0xE3B0U, nullptr, nullptr, true, 0},
    {0x120B8U, 1U, 0xCDF0U, "?AddRef@?$CRefCountImpl@VCWarpPalLockSubresourceExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalLockSubresourceExtension>::AddRef(void)", false, 0},
    {0x120B8U, 2U, 0xE560U, "?Release@?$CRefCountImpl@VCWarpPalLockSubresourceExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalLockSubresourceExtension>::Release(void)", false, 0},
    {0x120B8U, 3U, 0xE040U, nullptr, nullptr, true, 0},
    {0x120B8U, 4U, 0xEBB0U, nullptr, nullptr, true, 0},
    {0x120E0U, 0U, 0xE310U, nullptr, nullptr, true, 0},
    {0x120E0U, 1U, 0xCDF0U, "?AddRef@?$CRefCountImpl@VCWarpPalFlushAndWaitExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalFlushAndWaitExtension>::AddRef(void)", false, 0},
    {0x120E0U, 2U, 0xE560U, "?Release@?$CRefCountImpl@VCWarpPalFlushAndWaitExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalFlushAndWaitExtension>::Release(void)", false, 0},
    {0x120E0U, 3U, 0xDD80U, nullptr, nullptr, true, 0},
    {0x12100U, 0U, 0xE270U, nullptr, nullptr, true, 0},
    {0x12100U, 1U, 0xCDF0U, "?AddRef@?$CRefCountImpl@VCWarpPalCreateSharedResourceExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalCreateSharedResourceExtension>::AddRef(void)", false, 0},
    {0x12100U, 2U, 0xE560U, "?Release@?$CRefCountImpl@VCWarpPalCreateSharedResourceExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalCreateSharedResourceExtension>::Release(void)", false, 0},
    {0x12100U, 3U, 0xCEB0U, nullptr, nullptr, true, 0},
    {0x12100U, 4U, 0xDC20U, nullptr, nullptr, true, 0},
    {0x12128U, 0U, 0xE1D0U, nullptr, nullptr, true, 0},
    {0x12128U, 1U, 0xCDC0U, "?AddRef@?$CRefCountImpl@VCWarpPalAlphaBltExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalAlphaBltExtension>::AddRef(void)", false, 0},
    {0x12128U, 2U, 0xE4F0U, "?Release@?$CRefCountImpl@VCWarpPalAlphaBltExtension@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefCountImpl<class CWarpPalAlphaBltExtension>::Release(void)", false, 0},
    {0x12128U, 3U, 0xCF70U, nullptr, nullptr, true, 0},
    {0x12128U, 4U, 0xE670U, nullptr, nullptr, true, 0},
    {0x12128U, 5U, 0xE6A0U, nullptr, nullptr, true, 0},
    {0x12128U, 6U, 0xE7A0U, nullptr, nullptr, true, 0},
    {0x12128U, 7U, 0xD9D0U, nullptr, nullptr, true, 0},
    {0x12128U, 8U, 0xEAF0U, nullptr, nullptr, true, 0},
    {0x12170U, 0U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 4U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 5U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 6U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 7U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12170U, 8U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121B8U, 0U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121B8U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121B8U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121B8U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121B8U, 4U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121E0U, 0U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121E0U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121E0U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x121E0U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 0U, 0xE1D0U, "?QueryInterface@?$CWarpExtensionBase@VIWarpPalAlphaBltExtension@@@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl CWarpExtensionBase<class IWarpPalAlphaBltExtension>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x12200U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 4U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 5U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 6U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 7U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12200U, 8U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12248U, 0U, 0xE270U, "?QueryInterface@?$CWarpExtensionBase@VIWarpPalCreateSharedResourceExtension@@@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl CWarpExtensionBase<class IWarpPalCreateSharedResourceExtension>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x12248U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12248U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12248U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12248U, 4U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12270U, 0U, 0xE310U, "?QueryInterface@?$CWarpExtensionBase@VIWarpPalFlushAndWaitExtension@@@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl CWarpExtensionBase<class IWarpPalFlushAndWaitExtension>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x12270U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12270U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12270U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12290U, 0U, 0xE3B0U, "?QueryInterface@?$CWarpExtensionBase@VIWarpPalLockSubresourceExtension@@@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl CWarpExtensionBase<class IWarpPalLockSubresourceExtension>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x12290U, 1U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12290U, 2U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12290U, 3U, 0x2280U, nullptr, nullptr, true, 0},
    {0x12290U, 4U, 0x2280U, nullptr, nullptr, true, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
